const fertilizerBags = [
  // {
  //   id: "printed-packaging",
  //   title: "Printed Fertilizer Bag",
  //   price: "₹ 32",
  //   unit: "Piece",
  //   rating: 4.7,
  //   reviews: 89,
  //    images: [
  //     "printedFertilizer1",
  //     "printedFertilizer2",
  //     "printedFertilizer3", 
  //   ],
  //   specs: [
  //     { label: "Minimum Order Quantity", value: "500 Piece" },
  //     { label: "Storage Capacity", value: "50 Kg" },
  //     { label: "Usage/Application", value: "Fertilizer Packaging" },
  //     { label: "Material", value: "BOPP" },
  //     { label: "Shape", value: "Rectangular" },
  //     { label: "Pattern", value: "Printed" },
  //     { label: "Brand", value: "All Pack Creation" },

  //   ], 
  // },
   {
    id: "5kgFertilizerBag",
    title: "5 Kg Fertilizer Bag",
    price: "₹ 21",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "CarousalSlider6.jpg", 
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "500 Piece" },
      { label: "Storage Capacity", value: "5 Kg" },
      { label: "Color", value: "White" },
      { label: "Material", value: "BOPP" },
      { label: "Usage/Applications", value: "Fertilizer Packaging" },
      { label: "Pattern", value: "Printed" },
      { label: "Brand", value: "Allpack" }, 
    ],
  },
   {
    id: "10kgFertilizerBag",
    title: "10Kg Printed Fertilizer Bag",
    price: "₹ 7",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "product3", 
      "printFertilizer3"
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "500 Piece" }, 
      { label: "Storage Capacity", value: "10 kg" },
      { label: "Shape", value: "Rectangular" },
      { label: "Material", value: "LDPE" },
      { label: "Usage/Application", value: "Fertilizer Packaging" }, 
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
   {
    id: "25kgFertilizerBag",
    title: "25Kg Fertilizer Bag",
    price: "₹ 27",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "25kgFertilizer1",
      "25kgFertilizer2",
      "25kgFertilizer3",
      "25kgFertilizer4",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "100 Piece" },
      { label: "Storage Capacity", value: "25 Kg" },
      { label: "Color", value: "White" },
      { label: "Material", value: "BOPP" },
      { label: "Usage/Applications", value: "Packaging" },
      { label: "Pattern", value: "Plain" },
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
  {
    id: "50kgFertilizerBag",
    title: "50 kg Fertilizer Bag",
    price: "₹ 28",
    unit: "Piece",
    rating: 4.7,
    reviews: 89,
    images: [
      "ppFertilizer4",
      "ppFertilizer1",
      "ppFertilizer2",
      "ppFertilizer3",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "100 Piece" },
      { label: "Storage Capacity", value: "50 Kg" },
      { label: "Color", value: "White" },
      { label: "Material", value: "PP" },
      { label: "Pattern", value: "Plain" },
      { label: "Brand", value: "Allpack Packaging" },
      { label: "Usage/Application", value: "Fertilizer Packaging" },
    ], 
  }, 
 
  {
    id: "whiteFertilizerBag",
    title: "White Fertilizer Packaging Bag",
    price: "₹ 32",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "whiteFertilizer1",
      "whiteFertilizer2",
      "whiteFertilizer3",
      "whiteFertilizer4",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "100 Piece" },
      { label: "Storage Capacity", value: "50 Kg" },
      { label: "Color", value: "White" },
      { label: "Material", value: "PP" },
      { label: "Usage/Applications", value: "Fertilizer Packaging" },
      { label: "Pattern", value: "Plain" },
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
   
  {
    id: "BOPPFertilizer",
    title: "BOPP Fertilizer Bag",
    price: "₹ 27",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "boppFertilizer1",
      "boppFertilizer2",
      "boppFertilizer3",
      "boppFertilizer4",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "100 Piece" },
      { label: "Storage Capacity", value: "25 Kg" },
      { label: "Color", value: "White" },
      { label: "Material", value: "BOPP" },
      { label: "Usage/Applications", value: "Packaging" },
      { label: "Pattern", value: "Plain" },
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
  {
    id: "agriFertilizer",
    title: "Agricultural Fertilizer Bags",
    price: "₹ 15",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "agriFertilizer1",
      "agriFertilizer2",
      "agriFertilizer3",
      "agriFertilizer4",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "1000 Piece" },
      { label: "Storage Capacity", value: "50 Kg" },
      { label: "Color", value: "White" },
      { label: "Material", value: "PP" },
      { label: "Usage/Applications", value: "Packaging" },
      { label: "Pattern", value: "Plain" },
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
  {
    id: "hdpeFertilizer",
    title: "HDPE Fertilizer Bag",
    price: "₹ 32",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "HDPEFertilizer1",
      "HDPEFertilizer2",
      "HDPEFertilizer3",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "1000 Piece" },
      { label: "Storage Capacity", value: "25 Kg" },
      { label: "Shape", value: "Rectangular" },
      { label: "Material", value: "HDPE" },
      { label: "Usage/Applications", value: "Fertilizer Packaging" },
      { label: "Pattern", value: "Printed" },
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
  {
    id: "5kgFertilizer",
    title: "5Kg Fertilizer Bag",
    price: "₹ 15",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "5kgFertilizer1",
      "5kgFertilizer2",
      "5kgFertilizer3",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "100 Piece" },
      { label: "Storage Capacity", value: "5 Kg" },
      { label: "Shape", value: "Rectangular" },
      { label: "Material", value: "HDPE" },
      { label: "Usage", value: "Fertilizer Packaging" },
      { label: "Pattern", value: "Printed" },
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
  {
    id: "25kgFertilizers",
    title: "25Kg Fertilizer Bag",
    price: "₹ 28",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "25kgFertilizers1",
      "25kgFertilizers2",
      "25kgFertilizers3",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "500 Piece" },
      { label: "Storage Capacity", value: "25 Kg" },
      { label: "Shape", value: "Rectangular" },
      { label: "Material", value: "BOPP" },
      { label: "Usage", value: "Fertilizer Packaging" },
      { label: "Pattern", value: "Printed" },
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
   {
    id: "printedFertilizers",
    title: "Printed Fertilizer Bag",
    price: "₹ 8",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "printFertilizer1",
      "printFertilizer2",
      "printFertilizer3",
      "printFertilizer4",
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "500 Piece" }, 
      { label: "Shape", value: "Rectangular" },
      { label: "Material", value: "BOPP" },
      { label: "Usage/Application", value: "Fertilizer Packaging" },
      { label: "Pattern", value: "Printed" },
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
  {
    id: "greenFertilizer",
    title: "Green Printed Fertilizer Bag",
    price: "₹ 8",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "greenFertilizer1", 
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "500 Piece" }, 
      { label: "Storage Capacity", value: "25 kg" },
      { label: "Colour", value: "Green" },
      { label: "Shape", value: "Rectangular" },
      { label: "Material", value: "BOPP" },
      { label: "Usage/Application", value: "Fertilizer Packaging" }, 
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
   {
    id: "25kgBopp",
    title: "25Kg BOPP Fertilizer Bag",
    price: "₹ 8",
    unit: "Piece",
    rating: null,
    reviews: null,
     images: [
      "printedFertilizer1", 
    ],
    specs: [
      { label: "Minimum Order Quantity", value: "1000 Piece" }, 
      { label: "Storage Capacity", value: "50 kg" },
      { label: "Design", value: "Printed" },
      { label: "Shape", value: "Rectangular" },
      { label: "Material", value: "BOPP" },
      { label: "Usage/Application", value: "Fertilizer Packaging" }, 
      { label: "Brand", value: "All Pack Creation" }, 
    ],
  },
 

];
  
export default fertilizerBags;
